config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do
    resources :comments
  end
    
  root "posts#index"

  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: { minimum: 5 }
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    
    
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params[:comment].permit(:name, :body))

        redirect_to post_path(@post)
        
    end    

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy

        redirect_to post_path(@post)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all.order('created_at DESC')
    end

    def new
        @post = Post.new
    end   
    
    def create
        @post = Post.new(post_params)

        if @post.save
            redirect_to @post
        else
            render 'new'  
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        @post = Post.find(params[:id])

        if @post.update(params[:post].permit(:title, :body))
            redirect_to @post
        else
            render 'edit'
        end
    end  
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy

        redirect_to root_path
    end

    private
        def post_params
            params.require(:post).permit(:title, :body)
        end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment_container">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
        <p class="comment_time">Added <%= time_ago_in_words(comment.created_at) %> Ago</p>
		<p class="comment_body"><%= comment.body %></p>
		
	

        <p class="delet_btn">
            <%= link_to 'Delete', [comment.post, comment],
                        method: :delete,
                        class: "button",
                        data: { confirm: 'Are you sure?'} %>
        </p>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	
	<%= f.label :body %>
	<%= f.text_area :body %>
	
	<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
	<title>BlogApp</title>
	<%= csrf_meta_tags %>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
			<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<div class="page_logo">
		<div class="wrapper">
			<h1>RoR blog</h1>
		</div>
	</div>

	<div id="main_menu">
		<div class="wrapper">
			<ul>
				<li>
					<%= link_to "Blog", root_path %>
				</li>
				<li><%= link_to "About", about_path %></li>
			</ul>
		</div>
	</div>
	
	<div id="main_content"> 
		<div class="wrapper">
			<div class="header">

				<% if current_page?(root_path) %>
					<p>All Posts</p>
				<% elsif current_page?(about_path) %>
					<p>About</p>
				<% else %>
					<%= link_to "Back to All Posts", root_path %>
				<% end %>
				

				<div class="button">
					<%= link_to "New Post", new_post_path %>
				</div>

			</div>

			<% flash.each do |name, msg|%>
				<%= content_tag(:div, msg, class: "alert") %>
			<% end %>

			<%= yield %>
		</div>
	</div>
	
	
</body>

</html>

app/views/pages/about.html.erb
<div class="about_section">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis posuere erat, et luctus tortor. Praesent volutpat lorem sed pulvinar aliquet. Donec laoreet ligula dui, eu ullamcorper ipsum pellentesque sed. Nunc congue vitae ipsum et vestibulum. Etiam metus elit, mollis vitae sem eu, tincidunt cursus augue. Curabitur lacinia auctor turpis, lacinia aliquam ligula rhoncus quis. Sed viverra elit a massa gravida tempus. Nulla hendrerit ipsum sit amet lacus rhoncus, eget viverra mauris tincidunt. Praesent ut laoreet nisl, eget rhoncus risus. Cras ac nisl tempus, eleifend nulla quis, ullamcorper lacus. Mauris tincidunt tortor nec est tempor, eu pretium nisi cursus. Sed dapibus imperdiet lectus in aliquet. Donec in eros sed purus tempor feugiat ac nec mi. Nulla iaculis venenatis metus, et tristique augue tincidunt porttitor.

Aenean at massa nec felis commodo mollis in et enim. Nullam dui risus, mattis eleifend urna nec, fringilla auctor ex. Quisque blandit eros ut quam convallis aliquet. Pellentesque at lectus metus. Etiam accumsan luctus viverra. Etiam bibendum turpis vel dolor ultrices, in porta augue ultrices. Nulla quis magna ut erat tristique rutrum ac non arcu. Vestibulum quis dapibus massa. Aenean iaculis ipsum quis ultrices molestie. Sed egestas nunc est, sed euismod nisl laoreet ut. Cras porta neque id molestie cursus. Pellentesque mollis convallis enim id condimentum. In at laoreet orci. Sed augue lacus, interdum ac accumsan vitae, tempor eu nibh. Nunc imperdiet risus erat, eget pulvinar ex ornare a. Praesent sed arcu at mi ultricies commodo ut ac enim.  </p>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <div id="errors">
            <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from savings</h2>
            <ul>
                <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div id="create">
        <%= f.label :title %>
        <%= f.text_field :title %>
        <%= f.label :body %>
        <%= f.text_area :body %>
        <%= f.submit %>
    </div>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
    <h1>Edit Posts</h1>

    <%= render 'form' %>   
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div class="post_item">
        <h2 class="title">
            <%= link_to post.title, post %>
        </h2>
        <p class="date">
            <%= post.created_at.strftime("%B, %d, %Y") %>
        </p>
    </div>
<% end %>

app/views/posts/new.html.erb
<div id="new_post_container">
    <h1>New post</h1>

    <%= render 'form' %>   
</div>

app/views/posts/show.html.erb
<div id="post_content">
    <h1 class="title">
        <%= @post.title %>
    </h1>

    <p class="date">
        Submitted <%= time_ago_in_words(@post.created_at) %> Ago
        <%= link_to 'Edit', edit_post_path(@post) %>
        <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?'} %>
    </p>
    
    <p class="body">
        <%= @post.body %>
    </p>

    <div class="comments">
        <h2><%= @post.comments.count %> Comments </h2>
        <%= render @post.comments %>
        <h3>Add a comment:</h3>
        <%= render "comments/form" %>
    </div>
</div>